name: nextstrain-hpai
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.12
  - snakemake=9.14
  - nextstrain-cli
  - augur=32.1
  - seqkit=2.12
  - iqtree
  - mafft
  - pandas=2.3
  - biopython=1.86
  - matplotlib=3.10
  - openpyxl
  - numpy
